2022-08-30 15:00:42,951 ERROR com.bankingservice.banking.exception.ApplicationExceptionHandler [http-nio-9191-exec-6] [a5af9765-13e7-408f-bb20-0cdb856da456] [549fa2e0-cfa5-4135-a899-5a27e35567d0] InsertionFailedException: [Ljava.lang.StackTraceElement;@7769e8eb
2022-08-30 15:01:02,563 ERROR com.bankingservice.banking.services.servicehelper.AccountServiceHelper [http-nio-9191-exec-7] [4864c0ca-e2bd-4c06-967e-a3ed0f472cf6] [1d0d3587-19eb-449e-b719-5aa43f6d6c60] [convertDtoToCardModel] user does not exist for userId: REG-115238854
2022-08-30 15:01:02,575 ERROR com.bankingservice.banking.exception.ApplicationExceptionHandler [http-nio-9191-exec-7] [4864c0ca-e2bd-4c06-967e-a3ed0f472cf6] [1d0d3587-19eb-449e-b719-5aa43f6d6c60] UserIdNotFoundException: [Ljava.lang.StackTraceElement;@429160b7
2022-08-30 15:25:39,415 ERROR com.bankingservice.banking.services.AccountService [main] [] [] [insertDetailsForRegistration] details insertion failed in db for request: RegisterRequestDTO(name=QquwRPOVIk, email=EcnQ6Z4ZoG, mobileNumber=5318202875219898624, userName=kEVheyET4s, password=h3ov7njRYX)
org.springframework.dao.DataIntegrityViolationException: 
	at mockit.internal.expectations.invocation.InvocationResult$ThrowableResult.produceResult(InvocationResult.java:41)
	at mockit.internal.expectations.invocation.InvocationResult.produceResult(InvocationResult.java:22)
	at mockit.internal.expectations.invocation.InvocationResults.produceResult(InvocationResults.java:124)
	at mockit.internal.expectations.Expectation.produceResult(Expectation.java:48)
	at mockit.internal.expectations.ReplayPhase.produceResult(ReplayPhase.java:108)
	at mockit.internal.expectations.ReplayPhase.handleInvocation(ReplayPhase.java:52)
	at mockit.internal.expectations.RecordAndReplayExecution.recordOrReplay(RecordAndReplayExecution.java:170)
	at com.bankingservice.banking.services.servicehelper.AccountServiceHelper.saveRegisterModel(AccountServiceHelper.java)
	at com.bankingservice.banking.services.AccountService.insertDetailsForRegistration(AccountService.java:45)
	at com.bankingservice.banking.services.AccountServiceTest.testInsertDetailsForRegistrationException(AccountServiceTest.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
2022-08-30 17:57:30,913 ERROR com.bankingservice.banking.services.servicehelper.AccountServiceHelper [http-nio-9191-exec-7] [95b1b3d9-d8bf-466c-80e5-3e27f72dd5de] [dce551ad-b8cc-4480-bfc3-1c395d4acfb0] [convertSetPinDtoToCardModel] card does not exist for card number: 3166094828102
2022-08-30 17:57:30,929 ERROR com.bankingservice.banking.exception.ApplicationExceptionHandler [http-nio-9191-exec-7] [95b1b3d9-d8bf-466c-80e5-3e27f72dd5de] [dce551ad-b8cc-4480-bfc3-1c395d4acfb0] CardNotFoundException: [Ljava.lang.StackTraceElement;@7f2e008
2022-08-30 18:27:38,891 ERROR com.bankingservice.banking.services.AccountService [main] [] [] [insertDetailsForRegistration] details insertion failed in db for request: RegisterRequestDTO(name=rezYCidUgz, email=xPL3kYrxRp, mobileNumber=7710270110553098764, userName=nfCC9kcb8y, password=VXalLEyQ9f)
org.springframework.dao.DataIntegrityViolationException: 
	at mockit.internal.expectations.invocation.InvocationResult$ThrowableResult.produceResult(InvocationResult.java:41)
	at mockit.internal.expectations.invocation.InvocationResult.produceResult(InvocationResult.java:22)
	at mockit.internal.expectations.invocation.InvocationResults.produceResult(InvocationResults.java:124)
	at mockit.internal.expectations.Expectation.produceResult(Expectation.java:48)
	at mockit.internal.expectations.ReplayPhase.produceResult(ReplayPhase.java:108)
	at mockit.internal.expectations.ReplayPhase.handleInvocation(ReplayPhase.java:52)
	at mockit.internal.expectations.RecordAndReplayExecution.recordOrReplay(RecordAndReplayExecution.java:170)
	at com.bankingservice.banking.services.servicehelper.AccountServiceHelper.saveRegisterModel(AccountServiceHelper.java)
	at com.bankingservice.banking.services.AccountService.insertDetailsForRegistration(AccountService.java:47)
	at com.bankingservice.banking.services.AccountServiceTest.testInsertDetailsForRegistrationException(AccountServiceTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
2022-08-30 18:31:26,002 ERROR com.bankingservice.banking.services.servicehelper.AccountServiceHelper [http-nio-9191-exec-7] [e2ac1e5c-0fb1-473f-b988-1d828274ea18] [040e6999-330f-4149-80da-b9fa6ef655a4] [setPin] card does not exist for card number: 51663137502
2022-08-30 18:31:26,022 ERROR com.bankingservice.banking.exception.ApplicationExceptionHandler [http-nio-9191-exec-7] [e2ac1e5c-0fb1-473f-b988-1d828274ea18] [040e6999-330f-4149-80da-b9fa6ef655a4] CardNotFoundException: [Ljava.lang.StackTraceElement;@709d8e38
